services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=alex230302

  postgres:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_PASSWORD=alex230302
      - POSTGRES_USER=kenik
    volumes:
      - ./src/main/resources/init.sql://docker-entrypoint-initdb.d/init.sql
    ports:
      - "43321:5432"

