services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=user

  postgres:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
    ports:
      - "43321:5432"

