services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=user

  postgres:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=bank
<<<<<<< HEAD
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
    volumes:
      - pg_data:/var/lib/postgresql/data
=======
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
>>>>>>> develop
    ports:
      - "5432:5432"

  app:
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/Bank-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bank
      - SPRING_DATA_REDIS_HOST=redis
volumes:
  pg_data:

